services:
  museumswiki:
    build:
      context: .
      dockerfile: Dockerfile
    image: museumswiki:latest
    container_name: museumswiki
    restart: unless-stopped
    ports:
      - "8085:80"
